### ISSUE TITLE
History npm module doesn't have a createHistory function with it anymore.

### ISSUE THREAD

**Issue by sreimer15** [ntilwalli/routingWithPushState#1]
Copying and pasting this example doesn't lead to a working driver
import createHistory from 'history' doesn't work anymore,
the modules seems to have split into two flavors CreateHashHistory and CreateBrowserHistory.

None of these flavors create all the requisite functions in the history object 
(It is missing the createLocation and createHref functions)
causing the router driver to throw this error
'makeHistoryDriver requires an valid history object ' +
            'containing createLocation(), createHref(), push(), and listen() methods'

Sorry, I just can't figure it out, how do I work around this? 
This might be a problem with the router driver as well. Also I know this repo is for educational purposes and am grateful no matter what.

**Comment by ntilwalli** [comment]
What version of History are you using?

**Comment by sreimer15** [comment]
I actually came back to update this. Sorry, I changed my history version to version 3 and everything works, your example has been really helpful.
One day i'll figure out what changed with history v4.

**Comment by ntilwalli** [comment]
👍
